.forecast_styles:
    - &forecast_label_base
      bg_opa: TRANSP
      text_font: nunito_18
      border_width: 0
      grid_cell_x_align: center
      grid_cell_y_align: center
      text_color: white

    - &forecast_label_base_lo
      bg_opa: TRANSP
      text_font: nunito_18
      grid_cell_x_align: center
      grid_cell_y_align: center
      border_width: 0
      text_color: dodgerblue
      #height: SIZE_CONTENT

    - &forecast_image_base
      height: SIZE_CONTENT

    - &forecast_container
      bg_color: slate_blue_gray
      bg_opa: COVER
      border_width: 2
      border_color: very_dark_gray
      radius: 10

lvgl:
  pages:
    - id: !extend main_page
      widgets:
        - container:
            id: ${uid}
            grid_cell_row_pos: ${row}
            grid_cell_column_pos: ${column}
            grid_cell_row_span: ${row_span | default(1)}
            grid_cell_column_span: ${column_span | default(1)}
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            <<: *forecast_container
            layout:
              type: grid
              grid_rows: [ fr(1), content, fr(1), fr(1) ]
              grid_columns: [ fr(1), fr(1), fr(1), fr(1), fr(1) ]
            widgets:
              ########  Day 0  ########
              - label:
                  id: forecast_day_0
                  <<: *forecast_label_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 1
                  text: ???
              - image:
                  id: forecast_condition_icon_0
                  <<: *forecast_image_base
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 1
                  src: unknown_100
              - label:
                  id: forecast_temperature_hi_0
                  <<: *forecast_label_base
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 1
                  text: "---°"
              - label:
                  id: forecast_temperature_lo_0
                  <<: *forecast_label_base_lo
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 1
                  text: "---°"
              
              ########  Day 1  ########
              - label:
                  id: forecast_day_1
                  <<: *forecast_label_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 1
                  grid_cell_column_span: 1
                  text: ???
              - image:
                  id: forecast_condition_icon_1
                  <<: *forecast_label_base
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 1
                  grid_cell_column_span: 1
                  src: unknown_100
              - label:
                  id: forecast_temperature_hi_1
                  <<: *forecast_label_base
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 1
                  grid_cell_column_span: 1
                  text: "---°"
              - label:
                  id: forecast_temperature_lo_1
                  <<: *forecast_label_base_lo
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 1
                  grid_cell_column_span: 1
                  text: "---°"

              ########  Day 2  ########
              - label:
                  id: forecast_day_2
                  <<: *forecast_label_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 1
                  text: ???
              - image:
                  id: forecast_condition_icon_2
                  <<: *forecast_label_base
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 1
                  src: unknown_100
              - label:
                  id: forecast_temperature_hi_2
                  <<: *forecast_label_base
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 1
                  text: "---°"
              - label:
                  id: forecast_temperature_lo_2
                  <<: *forecast_label_base_lo
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 1
                  text: "---°"

              ########  Day 3  ########
              - label:
                  id: forecast_day_3
                  <<: *forecast_label_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 3
                  grid_cell_column_span: 1
                  text: ???
              - image:
                  id: forecast_condition_icon_3
                  <<: *forecast_label_base
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 3
                  grid_cell_column_span: 1
                  src: unknown_100
              - label:
                  id: forecast_temperature_hi_3
                  <<: *forecast_label_base
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 3
                  grid_cell_column_span: 1
                  text: "---°"
              - label:
                  id: forecast_temperature_lo_3
                  <<: *forecast_label_base_lo
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 3
                  grid_cell_column_span: 1
                  text: "---°"

              ########  Day 4  ########
              - label:
                  id: forecast_day_4
                  <<: *forecast_label_base
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 4
                  grid_cell_column_span: 1
                  text: ???
              - image:
                  id: forecast_condition_icon_4
                  <<: *forecast_label_base
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 4
                  grid_cell_column_span: 1
                  src: unknown_100
              - label:
                  id: forecast_temperature_hi_4
                  <<: *forecast_label_base
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 4
                  grid_cell_column_span: 1
                  text: "---°"
              - label:
                  id: forecast_temperature_lo_4
                  <<: *forecast_label_base_lo
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 4
                  grid_cell_column_span: 1
                  text: "---°"